name: Publish to Hex

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package to Hex.pm
    runs-on: ubuntu-latest

    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Erlang/OTP and Rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          rebar3-version: 3.22.1

      - name: Authenticate Hex
        run: |
          mkdir -p ~/.config/rebar3
          cat <<EOF > ~/.config/rebar3/hex.config
#{<<"hexpm">> =>
    #{api_key => <<"${HEX_API_KEY}">>}}.
EOF

      - name: Publish to Hex.pm
        run: rebar3 hex publish --yes
