name: Publish to Hex

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package to Hex.pm
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Erlang/OTP and Rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          rebar3-version: 3.22.1

      - name: Publish to Hex.pm
        uses: erlangpack/github-action@v3
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

